#
#leaf add @12112018
#

export PROSLIC_API_DIR=drivers/char/pcm/proslic_api
include $(PROSLIC_API_DIR)/proslic_api_options.mk
include $(PROSLIC_API_DIR)/proslic_api_core.mk

obj-$(CONFIG_PROSLIC) += proslic_sys/ proslic_core/
